/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Approval } from '../model/models';
import { ApprovalDetail } from '../model/models';
import { ApprovalStatus } from '../model/models';
import { ApproveRequest } from '../model/models';
import { PageApproval } from '../model/models';
import { RejectRequest } from '../model/models';
import { RequestChangesRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApproveApprovalRequestParams {
    id: string;
    approveRequest?: ApproveRequest;
}

export interface GetApprovalRequestParams {
    id: string;
}

export interface ListApprovalsRequestParams {
    status?: ApprovalStatus;
    runId?: string;
    type?: string;
    page?: number;
    size?: number;
}

export interface RejectApprovalRequestParams {
    id: string;
    rejectRequest: RejectRequest;
}

export interface RequestApprovalChangesRequestParams {
    id: string;
    requestChangesRequest: RequestChangesRequest;
}


export interface ApprovalsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Approve a PENDING approval (Section 8.2\&#39;s only path to WAITING_APPROVAL -&gt; APPROVED).
     *
     * @endpoint post /approvals/{id}/approve
* @param requestParameters
     */
    approveApproval(requestParameters: ApproveApprovalRequestParams, extraHttpRequestParams?: any): Observable<Approval>;

    /**
     * Get an approval, its run, and the diff summary.
     *
     * @endpoint get /approvals/{id}
* @param requestParameters
     */
    getApproval(requestParameters: GetApprovalRequestParams, extraHttpRequestParams?: any): Observable<ApprovalDetail>;

    /**
     * List approvals (Section 10.2).
     *
     * @endpoint get /approvals
* @param requestParameters
     */
    listApprovals(requestParameters: ListApprovalsRequestParams, extraHttpRequestParams?: any): Observable<PageApproval>;

    /**
     * Reject a PENDING approval; the run moves to REJECTED and the task returns to READY.
     *
     * @endpoint post /approvals/{id}/reject
* @param requestParameters
     */
    rejectApproval(requestParameters: RejectApprovalRequestParams, extraHttpRequestParams?: any): Observable<Approval>;

    /**
     * Request changes on a PENDING approval. Section 8.2 has no run status for \&quot;changes requested\&quot; -- the approval keeps this distinct outcome, but the run is driven through the REJECTED edge so the task returns to READY for rework.
     *
     * @endpoint post /approvals/{id}/request-changes
* @param requestParameters
     */
    requestApprovalChanges(requestParameters: RequestApprovalChangesRequestParams, extraHttpRequestParams?: any): Observable<Approval>;

}
