/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChatRejectedSenderRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface RecordChatRejectedSenderRequestParams {
    chatRejectedSenderRequest: ChatRejectedSenderRequest;
}


export interface ChatServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Section 16 Phase 12 Track B: called by a chat trigger adapter (apps/telegram-adapter, apps/whatsapp-adapter) instead of creating a task, when a message arrives from a chat ID not on the operator allow-list. talos-api is the sole PostgreSQL writer, so this is the one write the adapter needs to satisfy the \&quot;produces ... an audit row\&quot; acceptance criterion -- it records provenance only, never the disallowed message\&#39;s contents.
     *
     * @endpoint post /chat/rejected-sender
* @param requestParameters
     */
    recordChatRejectedSender(requestParameters: RecordChatRejectedSenderRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
