/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MonthlyCostSummary } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetProjectMonthlyCostsRequestParams {
    id: string;
}


export interface CostsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Phase 14: monthly per-agent cost/usage totals for a project (the dashboard cost widget). Runs still in flight are excluded. A month with no priced runs (subscription-only or CustomShellAdapter activity) reports a null totalCostUsd rather than a fabricated zero.
     *
     * @endpoint get /projects/{id}/costs/monthly
* @param requestParameters
     */
    getProjectMonthlyCosts(requestParameters: GetProjectMonthlyCostsRequestParams, extraHttpRequestParams?: any): Observable<Array<MonthlyCostSummary>>;

}
