/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DlqDepth } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DashboardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Message count on talos.dlq (Section 11\&#39;s \&quot;alert surfaced in Command Center\&quot;). A passive queue lookup -- reads 0 on a fresh install before the orchestrator has declared the queue.
     *
     * @endpoint get /dashboard/dlq-depth
*/
    getDlqDepth(extraHttpRequestParams?: any): Observable<DlqDepth>;

}
