/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { InternalLogsRequest } from '../model/models';
import { InternalStatusRequest } from '../model/models';
import { InternalStepRequest } from '../model/models';
import { Run } from '../model/models';
import { RunContext } from '../model/models';
import { Step } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface InternalGetRunContextRequestParams {
    id: string;
}

export interface InternalIngestRunLogsRequestParams {
    id: string;
    internalLogsRequest: InternalLogsRequest;
}

export interface InternalRecordRunStepRequestParams {
    id: string;
    internalStepRequest: InternalStepRequest;
}

export interface InternalUpdateRunStatusRequestParams {
    id: string;
    internalStatusRequest: InternalStatusRequest;
}


export interface InternalServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Run + task + project + active parsed config, for orchestrator pipeline bootstrap.
     * 
     * @endpoint get /internal/v1/runs/{id}/context
* @param requestParameters
     */
    internalGetRunContext(requestParameters: InternalGetRunContextRequestParams, extraHttpRequestParams?: any): Observable<RunContext>;

    /**
     * Ingest a batch of log lines; persists then relays to any open SSE connection via Redis.
     * 
     * @endpoint post /internal/v1/runs/{id}/logs
* @param requestParameters
     */
    internalIngestRunLogs(requestParameters: InternalIngestRunLogsRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Record a run step\&#39;s start or completion.
     * 
     * @endpoint post /internal/v1/runs/{id}/steps
* @param requestParameters
     */
    internalRecordRunStep(requestParameters: InternalRecordRunStepRequestParams, extraHttpRequestParams?: any): Observable<Step>;

    /**
     * Transition a run\&#39;s status (validated against Section 8.2\&#39;s state machine).
     * 
     * @endpoint post /internal/v1/runs/{id}/status
* @param requestParameters
     */
    internalUpdateRunStatus(requestParameters: InternalUpdateRunStatusRequestParams, extraHttpRequestParams?: any): Observable<Run>;

}
