/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ArtifactKind } from '../model/models';
import { GitTokenResponse } from '../model/models';
import { InternalChangesRequest } from '../model/models';
import { InternalLogsRequest } from '../model/models';
import { InternalPullRequestRequest } from '../model/models';
import { InternalStatusRequest } from '../model/models';
import { InternalStepRequest } from '../model/models';
import { MemoryDocument } from '../model/models';
import { MemoryDocumentRequest } from '../model/models';
import { MemorySearchResponse } from '../model/models';
import { PullRequest } from '../model/models';
import { RetentionCandidatesResponse } from '../model/models';
import { Run } from '../model/models';
import { RunArtifact } from '../model/models';
import { RunContext } from '../model/models';
import { Step } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface InternalCreateRunPullRequestRequestParams {
    id: string;
    internalPullRequestRequest: InternalPullRequestRequest;
}

export interface InternalDeleteRunArtifactsRequestParams {
    id: string;
}

export interface InternalGetRunContextRequestParams {
    id: string;
}

export interface InternalGetRunGitTokenRequestParams {
    id: string;
}

export interface InternalGetRunRetentionCandidatesRequestParams {
    maxAgeDays?: number;
}

export interface InternalIngestProjectMemoryDocumentRequestParams {
    projectId: string;
    memoryDocumentRequest: MemoryDocumentRequest;
}

export interface InternalIngestRunLogsRequestParams {
    id: string;
    internalLogsRequest: InternalLogsRequest;
}

export interface InternalRecordRunChangesRequestParams {
    id: string;
    internalChangesRequest: InternalChangesRequest;
}

export interface InternalRecordRunStepRequestParams {
    id: string;
    internalStepRequest: InternalStepRequest;
}

export interface InternalSearchProjectMemoryRequestParams {
    projectId: string;
    query: string;
    limit?: number;
    budgetChars?: number;
}

export interface InternalUpdateRunStatusRequestParams {
    id: string;
    internalStatusRequest: InternalStatusRequest;
}

export interface InternalUploadRunArtifactRequestParams {
    id: string;
    kind: ArtifactKind;
    name: string;
    file: Blob;
}


export interface InternalServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Called once the runner supervisor has pushed branchName: opens the PR via the GitHub REST API, stores the pull_requests row, publishes pr.created, and transitions the run APPROVED -&gt; COMPLETED (Section 8.2).
     *
     * @endpoint post /internal/v1/runs/{id}/pull-request
* @param requestParameters
     */
    internalCreateRunPullRequest(requestParameters: InternalCreateRunPullRequestRequestParams, extraHttpRequestParams?: any): Observable<PullRequest>;

    /**
     * Delete every stored artifact for a run (Phase 16 extension of Phase 11\&#39;s retention sweep) -- called by the orchestrator once the runner supervisor has deleted the run\&#39;s workspace.
     *
     * @endpoint delete /internal/v1/runs/{id}/artifacts
* @param requestParameters
     */
    internalDeleteRunArtifacts(requestParameters: InternalDeleteRunArtifactsRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Run + task + project + active parsed config, for orchestrator pipeline bootstrap.
     *
     * @endpoint get /internal/v1/runs/{id}/context
* @param requestParameters
     */
    internalGetRunContext(requestParameters: InternalGetRunContextRequestParams, extraHttpRequestParams?: any): Observable<RunContext>;

    /**
     * Phase 9\&#39;s push credential flow: the decrypted GitHub token for this run\&#39;s project, plus repoUrl/defaultBranch, for the runner supervisor\&#39;s push step. 409 unless run.status &#x3D;&#x3D; APPROVED -- the server-side enforcement behind \&quot;unapproved run cannot push\&quot;.
     *
     * @endpoint get /internal/v1/runs/{id}/git-token
* @param requestParameters
     */
    internalGetRunGitToken(requestParameters: InternalGetRunGitTokenRequestParams, extraHttpRequestParams?: any): Observable<GitTokenResponse>;

    /**
     * Phase 11 (Section 8.3): terminal runs completed more than maxAgeDays ago with no OPEN pull request. The orchestrator is the only service that can reach both this endpoint and the runner supervisor, so it drives the actual workspace deletion via POST /workspaces/cleanup after calling this.
     *
     * @endpoint get /internal/v1/runs/retention-candidates
* @param requestParameters
     */
    internalGetRunRetentionCandidates(requestParameters: InternalGetRunRetentionCandidatesRequestParams, extraHttpRequestParams?: any): Observable<RetentionCandidatesResponse>;

    /**
     * Phase 13: ingest context.docs content discovered by the orchestrator. The API still owns masking, chunking, embedding, and persistence.
     *
     * @endpoint post /internal/v1/projects/{projectId}/memory/documents
* @param requestParameters
     */
    internalIngestProjectMemoryDocument(requestParameters: InternalIngestProjectMemoryDocumentRequestParams, extraHttpRequestParams?: any): Observable<MemoryDocument>;

    /**
     * Ingest a batch of log lines; persists then relays to any open SSE connection via Redis.
     *
     * @endpoint post /internal/v1/runs/{id}/logs
* @param requestParameters
     */
    internalIngestRunLogs(requestParameters: InternalIngestRunLogsRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Record the file-level diff summary captured by the runner supervisor (Section 8.1 step 8).
     *
     * @endpoint post /internal/v1/runs/{id}/changes
* @param requestParameters
     */
    internalRecordRunChanges(requestParameters: InternalRecordRunChangesRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Record a run step\&#39;s start or completion.
     *
     * @endpoint post /internal/v1/runs/{id}/steps
* @param requestParameters
     */
    internalRecordRunStep(requestParameters: InternalRecordRunStepRequestParams, extraHttpRequestParams?: any): Observable<Step>;

    /**
     * Phase 13: project-scoped memory retrieval for orchestrator prompt assembly. Results are filtered to the requested project and capped by the supplied prompt budget.
     *
     * @endpoint get /internal/v1/projects/{projectId}/memory/search
* @param requestParameters
     */
    internalSearchProjectMemory(requestParameters: InternalSearchProjectMemoryRequestParams, extraHttpRequestParams?: any): Observable<MemorySearchResponse>;

    /**
     * Transition a run\&#39;s status (validated against Section 8.2\&#39;s state machine).
     *
     * @endpoint post /internal/v1/runs/{id}/status
* @param requestParameters
     */
    internalUpdateRunStatus(requestParameters: InternalUpdateRunStatusRequestParams, extraHttpRequestParams?: any): Observable<Run>;

    /**
     * Upload one artifact file (Phase 16, Section 10.4\&#39;s reserved contract line). Called directly by the runner supervisor -- not relayed through the orchestrator -- using the shared service token (Appendix A already reserves TALOS_INTERNAL_API_TOKEN there for \&quot;artifact/log posts\&quot;). talos-api is the only writer to the configured ArtifactStore.
     *
     * @endpoint post /internal/v1/runs/{id}/artifacts
* @param requestParameters
     */
    internalUploadRunArtifact(requestParameters: InternalUploadRunArtifactRequestParams, extraHttpRequestParams?: any): Observable<RunArtifact>;

}
