/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Integration } from '../model/models';
import { IntegrationCreateRequest } from '../model/models';
import { TestIntegrationResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateIntegrationRequestParams {
    integrationCreateRequest: IntegrationCreateRequest;
}

export interface TestIntegrationRequestParams {
    id: string;
}


export interface IntegrationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Configure an integration (e.g. a GitHub PAT) -- the secret is encrypted and stored behind a secret_ref (Section 12.2).
     * 
     * @endpoint post /integrations
* @param requestParameters
     */
    createIntegration(requestParameters: CreateIntegrationRequestParams, extraHttpRequestParams?: any): Observable<Integration>;

    /**
     * List configured integrations (Section 10.2). Secrets are never returned.
     * 
     * @endpoint get /integrations
*/
    listIntegrations(extraHttpRequestParams?: any): Observable<Array<Integration>>;

    /**
     * Verify the stored credential works (e.g. calls GET /user against GitHub).
     * 
     * @endpoint post /integrations/{id}/test
* @param requestParameters
     */
    testIntegration(requestParameters: TestIntegrationRequestParams, extraHttpRequestParams?: any): Observable<TestIntegrationResponse>;

}
