/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MemoryDocument } from '../model/models';
import { MemoryDocumentRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface IngestProjectMemoryDocumentRequestParams {
    id: string;
    memoryDocumentRequest: MemoryDocumentRequest;
}


export interface MemoryServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Phase 13: ingest an operator note or context document into project-scoped memory. The API owns chunking, masking, embedding, and persistence; no Python service writes memory rows.
     *
     * @endpoint post /projects/{id}/memory/documents
* @param requestParameters
     */
    ingestProjectMemoryDocument(requestParameters: IngestProjectMemoryDocumentRequestParams, extraHttpRequestParams?: any): Observable<MemoryDocument>;

}
