/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateProjectRequest } from '../model/models';
import { PageProjectSummary } from '../model/models';
import { Project } from '../model/models';
import { ProjectConfig } from '../model/models';
import { ProjectDetail } from '../model/models';
import { ProjectEnvironment } from '../model/models';
import { ProjectStatus } from '../model/models';
import { SyncConfigRequest } from '../model/models';
import { UpdateProjectRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateProjectRequestParams {
    createProjectRequest: CreateProjectRequest;
}

export interface GetProjectRequestParams {
    id: string;
}

export interface ListProjectEnvironmentsRequestParams {
    id: string;
}

export interface ListProjectsRequestParams {
    status?: ProjectStatus;
    page?: number;
    size?: number;
}

export interface SyncProjectConfigRequestParams {
    id: string;
    syncConfigRequest: SyncConfigRequest;
}

export interface UpdateProjectRequestParams {
    id: string;
    updateProjectRequest: UpdateProjectRequest;
}


export interface ProjectsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Register a new project.
     *
     * @endpoint post /projects
* @param requestParameters
     */
    createProject(requestParameters: CreateProjectRequestParams, extraHttpRequestParams?: any): Observable<Project>;

    /**
     * Get a project, its active config, and its 5 most recent runs.
     *
     * @endpoint get /projects/{id}
* @param requestParameters
     */
    getProject(requestParameters: GetProjectRequestParams, extraHttpRequestParams?: any): Observable<ProjectDetail>;

    /**
     * The project\&#39;s deploy targets and their most recent Dokploy deployment status (Phase 10).
     *
     * @endpoint get /projects/{id}/environments
* @param requestParameters
     */
    listProjectEnvironments(requestParameters: ListProjectEnvironmentsRequestParams, extraHttpRequestParams?: any): Observable<Array<ProjectEnvironment>>;

    /**
     * List projects.
     *
     * @endpoint get /projects
* @param requestParameters
     */
    listProjects(requestParameters: ListProjectsRequestParams, extraHttpRequestParams?: any): Observable<PageProjectSummary>;

    /**
     * Validate and store a new talos.yaml version; deactivates the previous active version.
     *
     * @endpoint post /projects/{id}/sync-config
* @param requestParameters
     */
    syncProjectConfig(requestParameters: SyncProjectConfigRequestParams, extraHttpRequestParams?: any): Observable<ProjectConfig>;

    /**
     * Update project fields.
     *
     * @endpoint put /projects/{id}
* @param requestParameters
     */
    updateProject(requestParameters: UpdateProjectRequestParams, extraHttpRequestParams?: any): Observable<Project>;

}
