/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RecommendationResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetProjectRecommendationsRequestParams {
    id: string;
}


export interface RecommendationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Phase 14: advisory-only signals computed from this project\&#39;s run history -- a suggested agent, a cheapest-capable-agent hint, and risk flags for file areas that have repeatedly failed automated review. Surfaced in the task form and Command Center; never auto-selects an agent or auto-executes anything.
     *
     * @endpoint get /projects/{id}/recommendations
* @param requestParameters
     */
    getProjectRecommendations(requestParameters: GetProjectRecommendationsRequestParams, extraHttpRequestParams?: any): Observable<RecommendationResponse>;

}
