/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DeployTriggerResponse } from '../model/models';
import { Diff } from '../model/models';
import { PageLogEntry } from '../model/models';
import { PageRunSummary } from '../model/models';
import { ProjectEnvironment } from '../model/models';
import { PullRequest } from '../model/models';
import { Run } from '../model/models';
import { RunDetail } from '../model/models';
import { RunStatus } from '../model/models';
import { StartRunRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CancelRunRequestParams {
    id: string;
}

export interface DeployRunRequestParams {
    id: string;
}

export interface GetRunRequestParams {
    id: string;
}

export interface GetRunDeployStatusRequestParams {
    id: string;
}

export interface GetRunDiffRequestParams {
    id: string;
}

export interface GetRunLogsRequestParams {
    id: string;
    afterSequence?: number;
    size?: number;
}

export interface GetRunPullRequestRequestParams {
    id: string;
}

export interface ListRunsRequestParams {
    projectId?: string;
    status?: RunStatus;
    page?: number;
    size?: number;
}

export interface StartRunRequestParams {
    id: string;
    startRunRequest?: StartRunRequest;
}

export interface StreamRunEventsRequestParams {
    id: string;
}


export interface RunsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Cancel a non-terminal run (Section 8.2 cancel edge). Transitions the run to CANCELLED immediately and publishes run.cancel.requested so the orchestrator can kill the process tree for a run it is actively processing (Phase 6 extension of Section 11 -- see packages/contracts/events/run.cancel.requested.json). 
     * 
     * @endpoint post /runs/{id}/cancel
* @param requestParameters
     */
    cancelRun(requestParameters: CancelRunRequestParams, extraHttpRequestParams?: any): Observable<Run>;

    /**
     * Request a deploy of a COMPLETED run\&#39;s code (Phase 10). Creates a PENDING DEPLOY approval and does NOT call the deploy provider when approval is required (production always is, Section 12.2; staging follows talos.yaml\&#39;s deploy.approval_required) -- this is the server-side enforcement behind \&quot;deploy button disabled without approval\&quot;. Otherwise triggers immediately. 
     * 
     * @endpoint post /runs/{id}/deploy
* @param requestParameters
     */
    deployRun(requestParameters: DeployRunRequestParams, extraHttpRequestParams?: any): Observable<DeployTriggerResponse>;

    /**
     * Get a run and its steps.
     * 
     * @endpoint get /runs/{id}
* @param requestParameters
     */
    getRun(requestParameters: GetRunRequestParams, extraHttpRequestParams?: any): Observable<RunDetail>;

    /**
     * The current deploy target/status for this run\&#39;s project (re-resolved from talos.yaml each call). 404 if never requested.
     * 
     * @endpoint get /runs/{id}/deploy
* @param requestParameters
     */
    getRunDeployStatus(requestParameters: GetRunDeployStatusRequestParams, extraHttpRequestParams?: any): Observable<ProjectEnvironment>;

    /**
     * Get the run\&#39;s changed-file summary and full unified diff text (Section 8.1 step 8; Phase 8 Review Center). diff is null until the orchestrator\&#39;s REVIEWING step has recorded it via /internal/v1/runs/{id}/changes. 
     * 
     * @endpoint get /runs/{id}/diff
* @param requestParameters
     */
    getRunDiff(requestParameters: GetRunDiffRequestParams, extraHttpRequestParams?: any): Observable<Diff>;

    /**
     * Get a page of a run\&#39;s logs, optionally after a given sequence number.
     * 
     * @endpoint get /runs/{id}/logs
* @param requestParameters
     */
    getRunLogs(requestParameters: GetRunLogsRequestParams, extraHttpRequestParams?: any): Observable<PageLogEntry>;

    /**
     * The PR opened for this run after approval (Phase 9). 404 until PullRequestService has opened one. 
     * 
     * @endpoint get /runs/{id}/pull-request
* @param requestParameters
     */
    getRunPullRequest(requestParameters: GetRunPullRequestRequestParams, extraHttpRequestParams?: any): Observable<PullRequest>;

    /**
     * List agent runs.
     * 
     * @endpoint get /runs
* @param requestParameters
     */
    listRuns(requestParameters: ListRunsRequestParams, extraHttpRequestParams?: any): Observable<PageRunSummary>;

    /**
     * Start an agent run for a task (CREATED -&gt; QUEUED, publishes task.run.requested).
     * 
     * @endpoint post /tasks/{id}/start-run
* @param requestParameters
     */
    startRun(requestParameters: StartRunRequestParams, extraHttpRequestParams?: any): Observable<Run>;

    /**
     * Server-Sent Events stream of log/status/step events for a run (Section 10.3).
     * 
     * @endpoint get /runs/{id}/events/stream
* @param requestParameters
     */
    streamRunEvents(requestParameters: StreamRunEventsRequestParams, extraHttpRequestParams?: any): Observable<string>;

}
