/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PageLogEntry } from '../model/models';
import { PageRunSummary } from '../model/models';
import { Run } from '../model/models';
import { RunDetail } from '../model/models';
import { RunStatus } from '../model/models';
import { StartRunRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetRunRequestParams {
    id: string;
}

export interface GetRunLogsRequestParams {
    id: string;
    afterSequence?: number;
    size?: number;
}

export interface ListRunsRequestParams {
    projectId?: string;
    status?: RunStatus;
    page?: number;
    size?: number;
}

export interface StartRunRequestParams {
    id: string;
    startRunRequest?: StartRunRequest;
}

export interface StreamRunEventsRequestParams {
    id: string;
}


export interface RunsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get a run and its steps.
     * 
     * @endpoint get /runs/{id}
* @param requestParameters
     */
    getRun(requestParameters: GetRunRequestParams, extraHttpRequestParams?: any): Observable<RunDetail>;

    /**
     * Get a page of a run\&#39;s logs, optionally after a given sequence number.
     * 
     * @endpoint get /runs/{id}/logs
* @param requestParameters
     */
    getRunLogs(requestParameters: GetRunLogsRequestParams, extraHttpRequestParams?: any): Observable<PageLogEntry>;

    /**
     * List agent runs.
     * 
     * @endpoint get /runs
* @param requestParameters
     */
    listRuns(requestParameters: ListRunsRequestParams, extraHttpRequestParams?: any): Observable<PageRunSummary>;

    /**
     * Start an agent run for a task (CREATED -&gt; QUEUED, publishes task.run.requested).
     * 
     * @endpoint post /tasks/{id}/start-run
* @param requestParameters
     */
    startRun(requestParameters: StartRunRequestParams, extraHttpRequestParams?: any): Observable<Run>;

    /**
     * Server-Sent Events stream of log/status/step events for a run (Section 10.3).
     * 
     * @endpoint get /runs/{id}/events/stream
* @param requestParameters
     */
    streamRunEvents(requestParameters: StreamRunEventsRequestParams, extraHttpRequestParams?: any): Observable<string>;

}
