/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTaskRequest } from '../model/models';
import { MoveTaskRequest } from '../model/models';
import { PageTaskSummary } from '../model/models';
import { PatchTaskRequest } from '../model/models';
import { Task } from '../model/models';
import { TaskDetail } from '../model/models';
import { TaskStatus } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateTaskRequestParams {
    createTaskRequest: CreateTaskRequest;
}

export interface GetTaskRequestParams {
    id: string;
}

export interface ListTasksRequestParams {
    projectId?: string;
    status?: TaskStatus;
    page?: number;
    size?: number;
}

export interface MoveTaskRequestParams {
    id: string;
    moveTaskRequest: MoveTaskRequest;
}

export interface PatchTaskRequestParams {
    id: string;
    patchTaskRequest: PatchTaskRequest;
}


export interface TasksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a task in BACKLOG.
     *
     * @endpoint post /tasks
* @param requestParameters
     */
    createTask(requestParameters: CreateTaskRequestParams, extraHttpRequestParams?: any): Observable<Task>;

    /**
     * Get a task and its agent runs.
     *
     * @endpoint get /tasks/{id}
* @param requestParameters
     */
    getTask(requestParameters: GetTaskRequestParams, extraHttpRequestParams?: any): Observable<TaskDetail>;

    /**
     * List tasks.
     *
     * @endpoint get /tasks
* @param requestParameters
     */
    listTasks(requestParameters: ListTasksRequestParams, extraHttpRequestParams?: any): Observable<PageTaskSummary>;

    /**
     * Move a task to a new Kanban column and/or reorder it within one.
     *
     * @endpoint post /tasks/{id}/move
* @param requestParameters
     */
    moveTask(requestParameters: MoveTaskRequestParams, extraHttpRequestParams?: any): Observable<Task>;

    /**
     * Partially update task fields (not status — use /move).
     *
     * @endpoint patch /tasks/{id}
* @param requestParameters
     */
    patchTask(requestParameters: PatchTaskRequestParams, extraHttpRequestParams?: any): Observable<Task>;

}
