/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserRequest } from '../model/models';
import { UpdateUserRequest } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateUserRequestParams {
    createUserRequest: CreateUserRequest;
}

export interface UpdateUserRequestParams {
    id: string;
    updateUserRequest: UpdateUserRequest;
}


export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a user with an operator-set password (not a token-based email invite -- Talos has no mail infrastructure yet). OWNER only.
     *
     * @endpoint post /users
* @param requestParameters
     */
    createUser(requestParameters: CreateUserRequestParams, extraHttpRequestParams?: any): Observable<User>;

    /**
     * List users (Section 16 Phase 15). OWNER only.
     *
     * @endpoint get /users
*/
    listUsers(extraHttpRequestParams?: any): Observable<Array<User>>;

    /**
     * Change a user\&#39;s role and/or active status. OWNER only; an OWNER cannot change their own role or deactivate themselves through this endpoint (use another OWNER account).
     *
     * @endpoint patch /users/{id}
* @param requestParameters
     */
    updateUser(requestParameters: UpdateUserRequestParams, extraHttpRequestParams?: any): Observable<User>;

}
