/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';


export interface GithubWebhookRequestParams {
    xHubSignature256: string;
    xGitHubEvent: string;
    body: object;
}


export interface WebhooksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * GitHub webhook receiver (Section 10.2). No JWT -- authenticated by HMAC-SHA256 signature over the raw request body (X-Hub-Signature-256) against TALOS_GITHUB_WEBHOOK_SECRET (Section 10.1 conventions). pull_request closed/reopened events transition the matching pull_requests row (matched by html_url) to MERGED/CLOSED/OPEN, which is what releases the run\&#39;s workspace to the Phase 11 retention sweep. All other event types, and PRs Talos didn\&#39;t open, are acknowledged with 204 and ignored.
     *
     * @endpoint post /webhooks/github
* @param requestParameters
     */
    githubWebhook(requestParameters: GithubWebhookRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
