/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';


// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    WebhooksServiceInterface,
    GithubWebhookRequestParams
} from './webhooks.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class WebhooksService extends BaseService implements WebhooksServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * GitHub webhook receiver (Section 10.2). No JWT -- authenticated by HMAC-SHA256 signature over the raw request body (X-Hub-Signature-256) against TALOS_GITHUB_WEBHOOK_SECRET (Section 10.1 conventions). pull_request closed/reopened events transition the matching pull_requests row (matched by html_url) to MERGED/CLOSED/OPEN, which is what releases the run\&#39;s workspace to the Phase 11 retention sweep. All other event types, and PRs Talos didn\&#39;t open, are acknowledged with 204 and ignored.
     * @endpoint post /webhooks/github
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public githubWebhook(requestParameters: GithubWebhookRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public githubWebhook(requestParameters: GithubWebhookRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public githubWebhook(requestParameters: GithubWebhookRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public githubWebhook(requestParameters: GithubWebhookRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const xHubSignature256 = requestParameters?.xHubSignature256;
        if (xHubSignature256 === null || xHubSignature256 === undefined) {
            throw new Error('Required parameter xHubSignature256 was null or undefined when calling githubWebhook.');
        }
        const xGitHubEvent = requestParameters?.xGitHubEvent;
        if (xGitHubEvent === null || xGitHubEvent === undefined) {
            throw new Error('Required parameter xGitHubEvent was null or undefined when calling githubWebhook.');
        }
        const body = requestParameters?.body;
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling githubWebhook.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xHubSignature256 !== undefined && xHubSignature256 !== null) {
            localVarHeaders = localVarHeaders.set('X-Hub-Signature-256', String(xHubSignature256));
        }
        if (xGitHubEvent !== undefined && xGitHubEvent !== null) {
            localVarHeaders = localVarHeaders.set('X-GitHub-Event', String(xGitHubEvent));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/webhooks/github`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: body,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
