package dev.talos.integrations;

import dev.talos.audit.AuditService;
import dev.talos.common.ApiException;
import dev.talos.events.EventPublisher;
import dev.talos.integrations.dto.PrCreatedPayload;
import dev.talos.projects.Project;
import dev.talos.projects.ProjectRepository;
import dev.talos.runs.AgentRun;
import dev.talos.runs.GitChange;
import dev.talos.runs.GitChangeRepository;
import dev.talos.runs.RunService;
import dev.talos.runs.RunStatus;
import dev.talos.tasks.Task;
import dev.talos.tasks.TaskRepository;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Map;

/**
 * Section 8.1 step 11 / 8.4: opens the PR after approval and completes the run (Section 8.2's
 * "APPROVED -> COMPLETED, Orchestrator (commit/push/PR)"). The runner supervisor has already
 * committed and pushed {@code branchName} by the time this runs (see Phase 9's git-token/push
 * flow) -- this service only has to talk to GitHub and finish the run.
 */
@Service
public class PullRequestService {

	private final PullRequestRepository pullRequestRepository;
	private final GitChangeRepository gitChangeRepository;
	private final TaskRepository taskRepository;
	private final ProjectRepository projectRepository;
	private final GitHubClient gitHubClient;
	private final IntegrationService integrationService;
	private final RunService runService;
	private final AuditService auditService;
	private final EventPublisher eventPublisher;

	public PullRequestService(PullRequestRepository pullRequestRepository, GitChangeRepository gitChangeRepository,
			TaskRepository taskRepository, ProjectRepository projectRepository, GitHubClient gitHubClient,
			IntegrationService integrationService, RunService runService, AuditService auditService,
			EventPublisher eventPublisher) {
		this.pullRequestRepository = pullRequestRepository;
		this.gitChangeRepository = gitChangeRepository;
		this.taskRepository = taskRepository;
		this.projectRepository = projectRepository;
		this.gitHubClient = gitHubClient;
		this.integrationService = integrationService;
		this.runService = runService;
		this.auditService = auditService;
		this.eventPublisher = eventPublisher;
	}

	@Transactional
	public PullRequest createForRun(AgentRun run, String branchName, String commitSha) {
		if (run.getStatus() != RunStatus.APPROVED) {
			throw new ApiException(HttpStatus.CONFLICT, "RUN_NOT_APPROVED",
					"Run %s is not APPROVED (currently %s) -- a PR can only be opened for an approved run"
							.formatted(run.getId(), run.getStatus()));
		}

		Task task = taskRepository.findById(run.getTaskId())
				.orElseThrow(() -> new ApiException(HttpStatus.NOT_FOUND, "TASK_NOT_FOUND", "Task not found"));
		Project project = projectRepository.findById(run.getProjectId())
				.orElseThrow(() -> new ApiException(HttpStatus.NOT_FOUND, "PROJECT_NOT_FOUND", "Project not found"));
		GitHubRepoRef repoRef = GitHubRepoRef.parse(project.getRepoUrl());
		String token = integrationService.resolveGitHubToken();

		List<GitChange> changes = gitChangeRepository.findByRunId(run.getId());
		String body = prBody(run, task, changes, commitSha);

		GitHubClient.PullRequestResult result = gitHubClient.createPullRequest(token, repoRef.owner(),
				repoRef.repo(), branchName, project.getDefaultBranch(), task.getTitle(), body);

		PullRequest pullRequest = pullRequestRepository
				.save(new PullRequest(run.getId(), "github", result.number(), result.htmlUrl()));

		auditService.record(null, "run.pr.created", "run", run.getId(),
				Map.of("prNumber", result.number(), "prUrl", result.htmlUrl()));
		eventPublisher.publish("pr.created", new PrCreatedPayload(run.getId(), result.htmlUrl(), result.number()));

		runService.transitionRun(run, RunStatus.COMPLETED, null, null);

		return pullRequest;
	}

	/** Section 8.4's PR body template: task link, run link, diffstat, test results, "Generated by Talos" footer. */
	private String prBody(AgentRun run, Task task, List<GitChange> changes, String commitSha) {
		int additions = changes.stream().mapToInt(GitChange::getAdditions).sum();
		int deletions = changes.stream().mapToInt(GitChange::getDeletions).sum();
		return """
				%s

				**Talos task:** /tasks/%s
				**Talos run:** /runs/%s
				**Commit:** %s
				**Diffstat:** %d file(s) changed, +%d/-%d
				**Tests:** %s

				---
				Generated by Talos
				""".formatted(task.getDescription() == null ? "" : task.getDescription(), task.getId(), run.getId(),
				commitSha, changes.size(), additions, deletions, run.getTestStatus());
	}
}
