/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgentStat {
    agentKey: string;
    totalRuns: number;
    completedRuns: number;
    riskFlaggedRuns: number;
    successRate: number;
    avgCostUsd?: number;
}
