/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApprovalStatus } from './approvalStatus';


export interface Approval {
    id: string;
    taskId: string;
    runId: string;
    approvalType: string;
    requestedAction: string;
    status: ApprovalStatus;
    requestedBy?: string;
    approvedBy?: string;
    approvedAt?: string;
    notes?: string;
    expiresAt?: string;
    createdAt: string;
    /**
     * Phase 10 -- set only on DEPLOY-type approvals; which environment this approval gates.
     */
    environment?: string;
}
export namespace Approval {
}
