/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitChangeSummary } from './gitChangeSummary';
import { Run } from './run';
import { Approval } from './approval';


export interface ApprovalDetail {
    approval: Approval;
    run: Run;
    changes: Array<GitChangeSummary>;
}
