/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Section 4.2\'s artifact classes (Phase 16).
 */
export const ArtifactKind = {
    DIFF_PATCH: 'DIFF_PATCH',
    TRANSCRIPT: 'TRANSCRIPT',
    TEST_REPORT: 'TEST_REPORT',
    GENERATED_DOC: 'GENERATED_DOC'
} as const;
export type ArtifactKind = typeof ArtifactKind[keyof typeof ArtifactKind];
