/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatRejectedSenderRequest {
    channel: ChatRejectedSenderRequest.ChannelEnum;
    chatId: string;
}
export namespace ChatRejectedSenderRequest {
    export const ChannelEnum = {
        TELEGRAM: 'TELEGRAM',
        WHATSAPP: 'WHATSAPP'
    } as const;
    export type ChannelEnum = typeof ChannelEnum[keyof typeof ChannelEnum];
}
