/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface CreateUserRequest {
    email: string;
    name: string;
    password: string;
    role: Role;
}
export namespace CreateUserRequest {
}
