/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskPriority } from './taskPriority';
import { TaskRiskLevel } from './taskRiskLevel';


export interface CreateTaskRequest { 
    projectId: string;
    title: string;
    description?: string;
    priority?: TaskPriority;
    riskLevel?: TaskRiskLevel;
    /**
     * Provenance, e.g. DASHBOARD (default) | WEBHOOK | TELEGRAM | WHATSAPP (Section 16 Phase 12 Track B). Unrecognized values fall back to DASHBOARD.
     */
    source?: string;
}
export namespace CreateTaskRequest {
}


