/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskPriority } from './taskPriority';
import { TaskRiskLevel } from './taskRiskLevel';


export interface CreateTaskRequest {
    projectId: string;
    title: string;
    description?: string;
    priority?: TaskPriority;
    riskLevel?: TaskRiskLevel;
    /**
     * Provenance, e.g. DASHBOARD (default) | WEBHOOK | TELEGRAM | WHATSAPP (Section 16 Phase 12 Track B). Unrecognized values fall back to DASHBOARD.
     */
    source?: string;
    /**
     * Phase 14: sets the task\'s preferred agent at creation time, e.g. following a recommendations hint -- an explicit operator choice, never auto-selected. Used by start-run as a fallback when the run request itself doesn\'t specify agentKey.
     */
    assignedAgentKey?: string;
}
export namespace CreateTaskRequest {
}
