/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectEnvironment } from './projectEnvironment';
import { Approval } from './approval';


/**
 * POST /runs/{id}/deploy\'s response -- discriminated on approvalRequired; approval is present only when true.
 */
export interface DeployTriggerResponse {
    approvalRequired: boolean;
    approval?: Approval;
    environment: ProjectEnvironment;
}
