/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitChangeSummary } from './gitChangeSummary';


export interface Diff {
    files: Array<GitChangeSummary>;
    /**
     * Unified diff text, or null if the run hasn\'t reached REVIEWING yet.
     */
    diff?: string;
}
