/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorError { 
    /**
     * SCREAMING_SNAKE error code enumerated in this spec.
     */
    code: string;
    message: string;
    details?: { [key: string]: any; };
}

