/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitChangeType } from './gitChangeType';


export interface GitChange {
    filePath: string;
    changeType: GitChangeType;
    additions: number;
    deletions: number;
}
export namespace GitChange {
}
