/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GitChangeType = {
    ADDED: 'ADDED',
    MODIFIED: 'MODIFIED',
    DELETED: 'DELETED',
    RENAMED: 'RENAMED'
} as const;
export type GitChangeType = typeof GitChangeType[keyof typeof GitChangeType];
