/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitChangeType } from './gitChangeType';


/**
 * Output-only counterpart to GitChange (Phase 8): adds the Section 12.1 post-run policy scan result, shown in the Review Center\'s file list and risk panel.
 */
export interface GitChangeSummary {
    filePath: string;
    changeType: GitChangeType;
    additions: number;
    deletions: number;
    riskFlagged: boolean;
    /**
     * The policy.yaml/talos.yaml pattern that flagged this file, if any.
     */
    matchedPattern?: string;
}
export namespace GitChangeSummary {
}
