/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Internal-only (Section 10.4) -- never reachable from /api/v1/_**.
 */
export interface GitTokenResponse { 
    token: string;
    authMode: string;
    repoUrl: string;
    defaultBranch: string;
}

