/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InternalLogEntry } from './internalLogEntry';


export interface InternalLogsRequest {
    entries: Array<InternalLogEntry>;
}
