/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TestStatus } from './testStatus';
import { RunStatus } from './runStatus';


/**
 * Phase 6 extension: optional fields let the orchestrator attach whichever run details it just produced (workspace_path/branchName after workspace prep, prompt/exitCode after agent execution, testStatus after the test command) to the same transition call that reports the status change, instead of a separate endpoint per field. Phase 14 adds inputTokens/ outputTokens/costUsd/costModel, reported alongside exitCode. The API nulls costUsd for provider_auth_mode=subscription_local runs regardless of what\'s sent here (Section 13).
 */
export interface InternalStatusRequest {
    status: RunStatus;
    errorMessage?: string;
    testStatus?: TestStatus;
    workspacePath?: string;
    branchName?: string;
    prompt?: string;
    summary?: string;
    exitCode?: number;
    inputTokens?: number;
    outputTokens?: number;
    costUsd?: number;
    costModel?: string;
}
export namespace InternalStatusRequest {
}
