/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogStream } from './logStream';


export interface InternalLogEntry {
    stream: LogStream;
    sequence: number;
    message: string;
    timestamp: string;
}
export namespace InternalLogEntry {
}
