/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Section 10.2 -- secrets are never included (they live behind SecretValue, referenced only by secret_ref).
 */
export interface Integration { 
    id: string;
    /**
     * \'github\', \'dokploy\', \'anthropic\', ...
     */
    type: string;
    name: string;
    configJson?: { [key: string]: any; };
    enabled: boolean;
    createdAt: string;
}

