/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StepType } from './stepType';
import { StepStatus } from './stepStatus';


export interface InternalStepRequest { 
    stepType: StepType;
    status: StepStatus;
    summary?: string;
}
export namespace InternalStepRequest {
}


