/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RunStatus } from './runStatus';


export interface InternalStatusRequest { 
    status: RunStatus;
    errorMessage?: string;
}
export namespace InternalStatusRequest {
}


