/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitChange } from './gitChange';


export interface InternalChangesRequest {
    files: Array<GitChange>;
    /**
     * Path to diff.patch on the runner supervisor\'s local filesystem (Section 8.3). Not a durable API-owned reference -- no agent_runs column stores it (MinIO artifact storage is post-MVP); recorded in the run.changes.recorded audit event only.
     */
    diffArtifactRef?: string;
    /**
     * Phase 8: the full unified diff text (already computed by the runner supervisor), persisted onto agent_runs.diff_patch and served back via GET /runs/{id}/diff.
     */
    diffPatch?: string;
}
