/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LogStream = {
    STDOUT: 'STDOUT',
    STDERR: 'STDERR',
    SYSTEM: 'SYSTEM'
} as const;
export type LogStream = typeof LogStream[keyof typeof LogStream];
