/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemorySourceType } from './memorySourceType';


export interface MemorySearchResult {
    chunkId: string;
    documentId: string;
    sourceType: MemorySourceType;
    sourceRef: string;
    title: string;
    content: string;
    score: number;
}
export namespace MemorySearchResult {
}
