/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemorySourceType } from './memorySourceType';


export interface MemoryDocument {
    id: string;
    projectId: string;
    sourceType: MemorySourceType;
    sourceRef: string;
    title: string;
    createdAt: string;
}
export namespace MemoryDocument {
}
