/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const MemorySourceType = {
    RUN_SUMMARY: 'RUN_SUMMARY',
    OPERATOR_NOTE: 'OPERATOR_NOTE',
    CONTEXT_DOC: 'CONTEXT_DOC'
} as const;
export type MemorySourceType = typeof MemorySourceType[keyof typeof MemorySourceType];
