/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemorySourceType } from './memorySourceType';


export interface MemoryDocumentRequest {
    sourceType: MemorySourceType;
    /**
     * Operator-controlled reference such as a doc path, note id, or external URL.
     */
    sourceRef?: string;
    title?: string;
    /**
     * Plaintext content; talos-api masks common secret shapes before persistence.
     */
    content: string;
}
export namespace MemoryDocumentRequest {
}
