/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorError } from './errorError';


/**
 * Error envelope returned on every non-2xx response (Section 10.1).
 */
export interface ModelError { 
    error: ErrorError;
}

