/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MonthlyCostSummary {
    agentKey: string;
    /**
     * YYYY-MM, UTC.
     */
    month: string;
    /**
     * Null when no run in this (agentKey, month) bucket has a priced cost.
     */
    totalCostUsd?: number;
    totalInputTokens: number;
    totalOutputTokens: number;
    runCount: number;
    subscriptionRunCount: number;
}
