/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskStatus } from './taskStatus';


export interface MoveTaskRequest {
    status: TaskStatus;
    boardPosition: number;
}
export namespace MoveTaskRequest {
}
