/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RunSummary } from './runSummary';


export interface PageRunSummary {
    content: Array<RunSummary>;
    page: number;
    size: number;
    totalElements: number;
}
