/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectSummary } from './projectSummary';


export interface PageProjectSummary { 
    content: Array<ProjectSummary>;
    page: number;
    size: number;
    totalElements: number;
}

