/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Approval } from './approval';


export interface PageApproval { 
    content: Array<Approval>;
    page: number;
    size: number;
    totalElements: number;
}

