/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogEntry } from './logEntry';


export interface PageLogEntry {
    content: Array<LogEntry>;
    page: number;
    size: number;
    totalElements: number;
}
