/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskPriority } from './taskPriority';
import { TaskRiskLevel } from './taskRiskLevel';


/**
 * Only non-null fields are applied. Status is not patchable here -- use /move.
 */
export interface PatchTaskRequest { 
    title?: string;
    description?: string;
    priority?: TaskPriority;
    riskLevel?: TaskRiskLevel;
    assignedAgentKey?: string;
}
export namespace PatchTaskRequest {
}


