/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectConfig } from './projectConfig';
import { ProjectStatus } from './projectStatus';
import { RunSummary } from './runSummary';


export interface ProjectDetail { 
    id: string;
    name: string;
    slug: string;
    repoUrl: string;
    defaultBranch: string;
    stackType: string;
    status: ProjectStatus;
    createdAt: string;
    updatedAt: string;
    activeConfig: ProjectConfig | null;
    /**
     * Every config version for this project, newest first (Phase 3 acceptance -- version history retained and visible).
     */
    configHistory: Array<ProjectConfig>;
    recentRuns: Array<RunSummary>;
}
export namespace ProjectDetail {
}


