/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeployStatus } from './deployStatus';


/**
 * Phase 10 -- a project\'s deploy target, synced from talos.yaml\'s deploy: block each time a deploy is requested.
 */
export interface ProjectEnvironment { 
    id: string;
    projectId: string;
    environment: string;
    provider: string;
    appId: string;
    approvalRequired: boolean;
    lastDeployStatus?: DeployStatus;
    lastDeployedAt?: string;
    lastRunId?: string;
}
export namespace ProjectEnvironment {
}


