/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectConfig {
    id: string;
    projectId: string;
    configYaml: string;
    parsedJson: { [key: string]: any; };
    version: number;
    active: boolean;
    createdAt: string;
}
