/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectConfig } from './projectConfig';
import { ProjectStatus } from './projectStatus';
import { RunSummary } from './runSummary';


export interface ProjectDetail { 
    id: string;
    name: string;
    slug: string;
    repoUrl: string;
    defaultBranch: string;
    stackType: string;
    status: ProjectStatus;
    createdAt: string;
    updatedAt: string;
    activeConfig: ProjectConfig | null;
    recentRuns: Array<RunSummary>;
}
export namespace ProjectDetail {
}


