/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PullRequestStatus } from './pullRequestStatus';


export interface PullRequest { 
    id: string;
    runId: string;
    provider: string;
    prNumber?: number;
    url?: string;
    status: PullRequestStatus;
    createdAt: string;
}
export namespace PullRequest {
}


