/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentStat } from './agentStat';
import { RiskFlag } from './riskFlag';


export interface RecommendationResponse {
    /**
     * Null when the project has no run history yet.
     */
    suggestedAgentKey?: string;
    /**
     * Null when no agent has both a priced run and a success rate >= 50%.
     */
    cheapestCapableAgentKey?: string;
    agentStats: Array<AgentStat>;
    riskFlags: Array<RiskFlag>;
}
