/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RiskFlag {
    /**
     * The top-level path segment shared by the flagged files.
     */
    fileArea: string;
    riskFlaggedRunCount: number;
}

