/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Section 9.3/Phase 15: a strict hierarchy, OWNER > MAINTAINER > REVIEWER > VIEWER -- each role implies every permission of the ones after it.
 */
export const Role = {
    OWNER: 'OWNER',
    MAINTAINER: 'MAINTAINER',
    REVIEWER: 'REVIEWER',
    VIEWER: 'VIEWER'
} as const;
export type Role = typeof Role[keyof typeof Role];
