/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TestStatus } from './testStatus';
import { ReviewStatus } from './reviewStatus';
import { RunStatus } from './runStatus';


export interface Run { 
    id: string;
    taskId: string;
    projectId: string;
    status: RunStatus;
    agentKey: string;
    providerAuthMode: string;
    prompt?: string;
    branchName?: string;
    workspacePath?: string;
    summary?: string;
    testStatus: TestStatus;
    reviewStatus: ReviewStatus;
    errorMessage?: string;
    exitCode?: number;
    timeoutAt?: string;
    startedAt?: string;
    completedAt?: string;
    createdAt: string;
    updatedAt: string;
}
export namespace Run {
}


