/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArtifactKind } from './artifactKind';


export interface RunArtifact {
    id: string;
    kind: ArtifactKind;
    name: string;
    sizeBytes: number;
    contentType: string;
    createdAt: string;
}
export namespace RunArtifact {
}
