/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectSummary } from './projectSummary';
import { TaskSummary } from './taskSummary';
import { Run } from './run';


export interface RunContext { 
    run: Run;
    task: TaskSummary;
    project: ProjectSummary;
    /**
     * The active project_configs.parsed_json, or absent if the project has no active config.
     */
    activeConfig?: { [key: string]: any; };
}

