/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TestStatus } from './testStatus';
import { ReviewStatus } from './reviewStatus';
import { RunStatus } from './runStatus';
import { Step } from './step';


export interface RunDetail {
    id: string;
    taskId: string;
    projectId: string;
    status: RunStatus;
    agentKey: string;
    providerAuthMode: string;
    prompt?: string;
    branchName?: string;
    workspacePath?: string;
    summary?: string;
    testStatus: TestStatus;
    reviewStatus: ReviewStatus;
    errorMessage?: string;
    exitCode?: number;
    /**
     * Phase 14 (Section 16) normalized usage metadata; null when the adapter can\'t report it.
     */
    inputTokens?: number;
    outputTokens?: number;
    /**
     * Provider-reported price in USD. Always null for provider_auth_mode=subscription_local (Section 13) -- never a fabricated/estimated price.
     */
    costUsd?: number;
    costModel?: string;
    timeoutAt?: string;
    startedAt?: string;
    completedAt?: string;
    createdAt: string;
    updatedAt: string;
    steps: Array<Step>;
}
export namespace RunDetail {
}
