/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RunStatus } from './runStatus';


export interface RunSummary {
    id: string;
    taskId: string;
    status: RunStatus;
    agentKey: string;
    createdAt: string;
}
export namespace RunSummary {
}
