/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RunStatus = {
    CREATED: 'CREATED',
    QUEUED: 'QUEUED',
    PREPARING_WORKSPACE: 'PREPARING_WORKSPACE',
    RUNNING_AGENT: 'RUNNING_AGENT',
    RUNNING_TESTS: 'RUNNING_TESTS',
    REVIEWING: 'REVIEWING',
    WAITING_APPROVAL: 'WAITING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED'
} as const;
export type RunStatus = typeof RunStatus[keyof typeof RunStatus];
