/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RunSummary { 
    id: string;
    taskId: string;
    status: string;
    agentKey: string;
    createdAt: string;
}

