/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StartRunRequest { 
    /**
     * Defaults to the active talos.yaml\'s agents.preferred when omitted.
     */
    agentKey?: string;
    /**
     * Defaults to \"api_key\" when omitted.
     */
    authMode?: string;
}

