/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StepType } from './stepType';
import { StepStatus } from './stepStatus';


export interface Step {
    id: string;
    runId: string;
    stepType: StepType;
    status: StepStatus;
    summary?: string;
    startedAt?: string;
    completedAt?: string;
}
export namespace Step {
}
