/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const StepType = {
    WORKSPACE: 'WORKSPACE',
    AGENT: 'AGENT',
    TESTS: 'TESTS',
    REVIEW: 'REVIEW',
    PUSH: 'PUSH',
    PR: 'PR',
    DEPLOY: 'DEPLOY'
} as const;
export type StepType = typeof StepType[keyof typeof StepType];

