/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TaskRiskLevel = {
    NORMAL: 'NORMAL',
    HIGH: 'HIGH'
} as const;
export type TaskRiskLevel = typeof TaskRiskLevel[keyof typeof TaskRiskLevel];
