/**
 * Talos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TestStatus = {
    NOT_RUN: 'NOT_RUN',
    PASSED: 'PASSED',
    FAILED: 'FAILED',
    ERROR: 'ERROR'
} as const;
export type TestStatus = typeof TestStatus[keyof typeof TestStatus];

