/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


/**
 * Only non-null fields are applied.
 */
export interface UpdateUserRequest {
    role?: Role;
    active?: boolean;
}
export namespace UpdateUserRequest {
}
