/**
 * Talos API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectStatus } from './projectStatus';


export interface UpdateProjectRequest {
    name?: string;
    repoUrl?: string;
    defaultBranch?: string;
    stackType?: string;
    status?: ProjectStatus;
}
export namespace UpdateProjectRequest {
}
